version: '3.8'

services:
  vlm-docling:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vlm-docling
    ports:
      - "8879:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0,1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - TRANSFORMERS_CACHE=/app/.cache/huggingface
      - DOCLING_PERF_PAGE_BATCH_SIZE=8
    volumes:
      - ./main.py:/app/main.py
      - ./docling_service.py:/app/docling_service.py
      - huggingface-cache:/app/.cache/huggingface
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  huggingface-cache:
